name: security_rules_test

on: [pull_request, workflow_dispatch]

jobs:
  security_rules_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        JDK-version: ["11"]

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Java JDK をセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JDK-version }}
          distribution: "temurin"

      - name: パッケージインストール
        run: |
          npm config set legacy-peer-deps true
          npm ci

      - name: firebase-tools をインストール
        run: npm install firebase-tools

      - name: エミュレータの起動, テスト実行, カバレッジファイルの取得
        run: cd tests/emulator && npx firebase emulators:exec "vitest --root $GITHUB_WORKSPACE --silent && curl -o $GITHUB_WORKSPACE/firestoreSecurityRulesTestCoverageReport.json http://localhost:8880/emulator/v1/projects/demo-fir-react-testing-sample:ruleCoverage"

      # SonicGarden/firestore-rules-report-action をもとに、ローカルに取得した
      # セキュリティルールのカバレッジファイルを利用するCustom Action
      # 本家のCustomAction だとPRコメントまで対応できるっぽいのだが、何度か試してもコメントが追加されないので、
      # 出力する内容をファイルに保持しておき、次のStep でコメントを追加する
      - name: coverage request
        id: coverageRequest
        uses: y-uchiida/firestore-rules-report-action@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report-url: "${{github.workspace}}/firestoreSecurityRulesTestCoverageReport.json"

      - name: プルリクエストにコメントを追加
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const commentBody = fs.readFileSync(`${process.env.GITHUB_WORKSPACE}/pr_comment_body.txt`, 'utf-8').toString()
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
