name: security_rules_test

on: [pull_request, workflow_dispatch]

jobs:
  security_rules_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        JDK-version: ["11"]

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Java JDK をセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JDK-version }}
          distribution: "temurin"
          cache: gradle

      - name: パッケージインストール
        run: npm install

      - name: firebase-tools をインストール
        run: npm install firebase-tools

      - name: エミュレータの起動, テスト実行
        run: cd tests/emulator && npx firebase emulators:exec "vitest --root $GITHUB_WORKSPACE --silent"

      # エミュレータ動作中でないとレポートが取れないっぽいのでいったん保留
      # - name: coverage request
      #   id: coverageRequest
      #   uses: SonicGarden/firestore-rules-report-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     report-url: "http://localhost:8880/emulator/v1/projects/demo-fir-react-testing-sample:ruleCoverage"
